name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [v20.15.0]
    env:
      NEXT_WEBSITE_URL: ${{ secrets.NEXT_WEBSITE_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Create env file
      run: |
        echo "NEXT_WEBSITE_URL=${{ secrets.NEXT_WEBSITE_URL }}" >> .env.production
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env.production
      working-directory: ${{ github.workspace }}

    - name: Print contents of .env.production file
      run: cat .env.production

    - run: npm run build --if-present
    - name: cd to the project directory
      run: cd ~/actions-runner/_work/tabletalk/tabletalk
    - run: pm2 reload 2 0
